name: Push Build
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build-image:
    environment: default
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -   name: Checkout
          uses: actions/checkout@v3
      -   uses: actions/setup-java@v3
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
      -   name: Build and deploy
          run: |
            #!/bin/bash
            mvn clean install -s settings.xml  -B -Dmaven.repo.local=repo
      -   uses: actions/upload-artifact@v3
          with:
            name: sbom.json
            path: target/sbom.json
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@897ed5eab6ed058a474202017ada7f40bfa52940 # v1.0.0
        with:
          subject-path: "target/hacbs-test.jar"
